### ISSUE TITLE
README Example fails "getaddrinfo: nodename nor servname provided"

### ISSUE THREAD

**Issue by joelmoss** [ashmckenzie/percheron#2]
Using the example as provided in the README, and running the command `DEBUG=true percheron start consul-stack`, fails with:

```
D, [2015-05-21T19:10:53.422876 #49464] DEBUG -- : Processing 'master' unit
D, [2015-05-21T19:10:53.450326 #49464] DEBUG -- : Docker::Container.get(["consul-stack_master"]) - #<Excon::Errors::SocketError: getaddrinfo: nodename nor servname provided, or not known (SocketError)>
D, [2015-05-21T19:10:53.461634 #49464] DEBUG -- : Docker::Image.get(["progrium/consul:latest"]) - #<Excon::Errors::SocketError: getaddrinfo: nodename nor servname provided, or not known (SocketError)>

We are terribly sorry.. something unexpected occurred :(

--snip--

Info
----
Ruby: 2.2.2
Percheron: 0.7.10

Trace
-----
#<Excon::Errors::SocketError: getaddrinfo: nodename nor servname provided, or not known (SocketError)>

/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/socket.rb:166:in `getaddrinfo'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/socket.rb:166:in `connect'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/ssl_socket.rb:140:in `connect'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/socket.rb:28:in `initialize'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/ssl_socket.rb:9:in `initialize'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:380:in `new'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:380:in `socket'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:105:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/mock.rb:47:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:232:in `request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/idempotent.rb:22:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:255:in `rescue in request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:203:in `request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/idempotent.rb:22:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:255:in `rescue in request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:203:in `request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/idempotent.rb:22:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/middlewares/base.rb:10:in `error_call'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:255:in `rescue in request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/excon-0.40.0/lib/excon/connection.rb:203:in `request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/docker-api-1.21.4/lib/docker/connection.rb:40:in `request'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/docker-api-1.21.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/docker-api-1.21.4/lib/docker/image.rb:122:in `get'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/connection.rb:22:in `public_send'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/connection.rb:22:in `perform'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/connection.rb:18:in `perform'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/unit.rb:77:in `image'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/unit.rb:142:in `image_exists?'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/actions/create.rb:12:in `initialize'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/actions/start.rb:34:in `new'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/actions/start.rb:34:in `create!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/actions/start.rb:16:in `execute!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:61:in `block in start!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:129:in `block in exec_on_dependant_units_for'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:135:in `block in exec_on_units'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:135:in `each'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:135:in `exec_on_units'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:127:in `exec_on_dependant_units_for'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/stack.rb:59:in `start!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/lib/percheron/commands/start.rb:9:in `execute'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/percheron-0.7.10/bin/percheron:11:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/bin/percheron:23:in `load'
/usr/local/opt/rbenv/versions/2.2.2/bin/percheron:23:in `<main>'
```

**Comment by joelmoss** [comment]
OK, no matter. The example includes the following which won't work for those who `boot2docker` host does not exist, which for most it will not

```yaml
docker:
  host: "https://boot2docker:2376"
```

The `host` should probably just be removed from the example, as it works without.

**Comment by bhouse** [comment]
+1 had the same issue @ashmckenzie when following the quickstart for [percheron-rails](https://github.com/ashmckenzie/percheron-rails#quickstart)

removing the `host: "https://boot2docker:2376"` line fixed it
